name: Deploy Vite App with pnpm

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Vite App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        run: |
          npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build Vite app
        run: pnpm build

  deploy:
    name: Deploy to Yandex Cloud
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Install Yandex Cloud CLI
        run: |
          wget https://storage.yandexcloud.net/yandexcloud-yc-releases/stable/linux/amd64/yc
          chmod +x yc
          sudo mv yc /usr/local/bin/yc

      - name: Authenticate Yandex Cloud
        run: |
          echo ${{ secrets.YANDEX_CLOUD_KEY }} > key.json
          yc config credentials add --service-account-key key.json

      - name: Deploy to bucket
        run: |
          yc s3 cp --recursive dist/ s3://$BUCKET_NAME/
          yc s3 website set s3://$BUCKET_NAME --index-document index.html
